/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.x.fome.view;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author prisc
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private Loja lojaPanel = null; 
    private Pedidos pedidosPanel = null;
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        loja = new javax.swing.JMenu();
        carrinho = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        pedidos = new javax.swing.JMenu();
        confuguracoes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loja.setText("Loja");
        loja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lojaMouseClicked(evt);
            }
        });
        loja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lojaActionPerformed(evt);
            }
        });
        jMenuBar1.add(loja);

        carrinho.setText("Carrinho");
        jMenuBar1.add(carrinho);
        jMenuBar1.add(jMenu3);

        pedidos.setText("Pedidos");
        pedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedidosMouseClicked(evt);
            }
        });
        pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidosActionPerformed(evt);
            }
        });
        jMenuBar1.add(pedidos);

        confuguracoes.setText("Configurações");
        confuguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confuguracoesActionPerformed(evt);
            }
        });
        jMenuBar1.add(confuguracoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedidosMouseClicked
   
        if(pedidosPanel == null){
            pedidosPanel = new Pedidos();
            pedidosPanel.setBounds(0,0,400,400);  
            pedidosPanel.setBackground(Color.gray);
            this.setLayout(null);
            this.add(pedidosPanel);
            this.setSize(400,400);
        }else{
            pedidosPanel.setVisible(true);
            lojaPanel.setVisible(false);
        }
        
         
    }//GEN-LAST:event_pedidosMouseClicked

    private void pedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidosActionPerformed
         if(pedidosPanel == null){
            pedidosPanel = new Pedidos();
            pedidosPanel.setBounds(0,0,400,400);  
            pedidosPanel.setBackground(Color.gray);
            this.setLayout(null);
            this.add(pedidosPanel);
            this.setSize(400,400);
        }else{
            pedidosPanel.setVisible(true);
            lojaPanel.setVisible(false);
        }
    }//GEN-LAST:event_pedidosActionPerformed

    private void lojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lojaActionPerformed
        if(lojaPanel == null){
            lojaPanel = new Loja(this);
            lojaPanel.setBounds(0,0,400,400);
            lojaPanel.setBackground(Color.gray);
            this.setLayout(null);
            this.add(lojaPanel);
            this.setSize(400,400);
        }else{
            lojaPanel.setVisible(true);
            pedidosPanel.setVisible(false);
        }
    }//GEN-LAST:event_lojaActionPerformed

    private void lojaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lojaMouseClicked
        if(lojaPanel == null){
            lojaPanel = new Loja(this);
            lojaPanel.setBounds(0,0,400,400);
            lojaPanel.setBackground(Color.gray);
            this.setLayout(null);
            this.add(lojaPanel);
            this.setSize(400,400);
        }else{
            lojaPanel.setVisible(true);
            pedidosPanel.setVisible(false);
        }

    }//GEN-LAST:event_lojaMouseClicked

    private void confuguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confuguracoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confuguracoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu carrinho;
    private javax.swing.JMenu confuguracoes;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu loja;
    private javax.swing.JMenu pedidos;
    // End of variables declaration//GEN-END:variables
}
