/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.x.fome.view;

import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author prisc
 */
public class Loja extends javax.swing.JPanel {

    /**
     * Creates new form Loja
     */
    public Loja(JFrame jframe) {
        this.jFrame = jframe;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bebidaButton = new javax.swing.JButton();
        porcoesButton = new javax.swing.JButton();
        lanchesButton = new javax.swing.JButton();
        sobremesaButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("X-FOME");

        bebidaButton.setText("Bebidas");
        bebidaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bebidaButtonMouseClicked(evt);
            }
        });

        porcoesButton.setText("Porções");
        porcoesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                porcoesButtonMouseClicked(evt);
            }
        });
        porcoesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcoesButtonActionPerformed(evt);
            }
        });

        lanchesButton.setText("Lanches");
        lanchesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lanchesButtonMouseClicked(evt);
            }
        });

        sobremesaButton.setText("Sobremesa");
        sobremesaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sobremesaButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sobremesaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lanchesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(porcoesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bebidaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bebidaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(porcoesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lanchesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(sobremesaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void porcoesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcoesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porcoesButtonActionPerformed

    private void bebidaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bebidaButtonMouseClicked
        Produto pedido = new Produto(this.jFrame, true);
        pedido.setTipoProduto("  Bedidas");
        pedido.setVisible(true);
    }//GEN-LAST:event_bebidaButtonMouseClicked

    private void porcoesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_porcoesButtonMouseClicked
        Produto pedido = new Produto(this.jFrame, true);
        pedido.setTipoProduto("  Porcoes");
        pedido.setVisible(true);
    }//GEN-LAST:event_porcoesButtonMouseClicked

    private void lanchesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lanchesButtonMouseClicked
        Produto pedido = new Produto(this.jFrame, true);
        pedido.setTipoProduto("  Lanches");
        pedido.setVisible(true);
    }//GEN-LAST:event_lanchesButtonMouseClicked

    private void sobremesaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobremesaButtonMouseClicked
        Produto pedido = new Produto(this.jFrame, true);
        pedido.setTipoProduto("Sobremesas");
        pedido.setVisible(true);
    }//GEN-LAST:event_sobremesaButtonMouseClicked

    private javax.swing.JFrame jFrame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bebidaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lanchesButton;
    private javax.swing.JButton porcoesButton;
    private javax.swing.JButton sobremesaButton;
    // End of variables declaration//GEN-END:variables
}
